name: Test
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11.0
          - macos-latest
          - windows-latest
          - ubuntu-20.04
          - ubuntu-latest
        python-version: [ 3.9, 3.10, 3.11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
      - run: |
          poetry install
          poetry run pytest
        shell: bash
